# Generated by Django 4.1.6 on 2023-11-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst', models.CharField(max_length=50, verbose_name='gst')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('date', models.CharField(max_length=50, verbose_name='date')),
            ],
            options={
                'verbose_name_plural': 'UserDetails',
            },
        ),
    ]
